---

- hosts: ios
  gather_facts: false
  connection: local

  tasks:

  - name: Show run command 
    ios_command:
       commands: show run
    register: config

  - name: Save output to /etc/ansible/backups
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "/etc/ansible/backups/{{ inventory_hostname }}.txt"
