
---

- hosts: ios
  gather_facts: false
  connection: local

  tasks:

  - name: Show run command 
    ios_command:
       commands: show version
    register: version

  - name: Save output to /etc/ansible/backups
    copy:
      content: "{{ version.stdout[0] }}"
      dest: "/etc/ansible/{{ inventory_hostname }}.txt"
    debug:
      var: version

